#!/usr/bin/env python3
"""build_css.py - generate render/tokens.css (CSS custom properties) from tokens.json.

Usage:
    python tools/build_css.py            # writes render/tokens.css next to tokens.json
    python tools/build_css.py --check    # exit 1 if render/tokens.css is out of date

Rules:
  - Every key of every group becomes --{group}-{key} (underscores become dashes).
  - Keys starting with "_" are notes and are skipped; lists and nested objects too.
  - Numbers get "px", except keys ending in _weight, _arcsize, and the groups
    "meta" and "font" (weights are unitless), and type.display_line_alt.
  - Strings are written as they are (colors, gradients, em tracking, "20px").
  - "%%group.key%%" references are resolved against tokens.json.
  - Values that look like placeholders ([[CONFIRMAR...]]) are skipped.
Stdlib only.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

KIT = Path(__file__).resolve().parents[1]
UNITLESS_SUFFIXES = ("_weight", "_arcsize")
UNITLESS_KEYS = {"type.display_line_alt"}
SKIP_GROUPS = {"meta", "dark_mode", "footer", "assets"}
REF = re.compile(r"%%([a-z_]+)\.([a-z0-9_]+)%%")


def resolve(value, tokens):
    if not isinstance(value, str):
        return value
    def sub(m):
        return str(tokens.get(m.group(1), {}).get(m.group(2), m.group(0)))
    return REF.sub(sub, value)


def css_value(group: str, key: str, value) -> str | None:
    if isinstance(value, bool) or isinstance(value, (list, dict)) or value is None:
        return None
    if isinstance(value, (int, float)):
        if group == "font" or key == "weight" or key.endswith(UNITLESS_SUFFIXES) or f"{group}.{key}" in UNITLESS_KEYS:
            return f"{value:g}"
        return f"{value:g}px"
    value = str(value).strip()
    if not value or "[[" in value:
        return None
    return value


def build(tokens: dict) -> str:
    lines = [
        "/* GENERATED by tools/build_css.py from tokens.json. Do not edit by hand. */",
        f"/* {tokens.get('meta', {}).get('brand_name', '')} email kit {tokens.get('meta', {}).get('kit_version', '')} */",
        ":root{",
    ]
    for group, entries in tokens.items():
        if group.startswith("_") or not isinstance(entries, dict) or group in SKIP_GROUPS:
            continue
        lines.append(f"  /* {group} */")
        for key, value in entries.items():
            if key.startswith("_"):
                continue
            v = css_value(group, key, resolve(value, tokens))
            if v is None:
                continue
            name = f"--{group}-{key}".replace("_", "-")
            lines.append(f"  {name}:{v};")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="fail if render/tokens.css is stale")
    args = ap.parse_args(argv)
    tokens = json.loads((KIT / "tokens.json").read_text(encoding="utf-8"))
    css = build(tokens)
    out = KIT / "render" / "tokens.css"
    if args.check:
        current = out.read_text(encoding="utf-8") if out.exists() else ""
        if current != css:
            print("render/tokens.css is out of date: run python tools/build_css.py")
            return 1
        print("render/tokens.css is up to date")
        return 0
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(css, encoding="utf-8")
    count = css.count(";")
    print(f"wrote {out} ({count} properties)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
